var five = 5;
console.log("Test 1: five is equal to 5?");
var ten = 10;
console.log(five == 5);
console.log("test 2: ten is equal to 10?");
console.log(ten == 10);
console.log("Test 3: five is not equal to 10?");
console.log(five != 10);
console.log("Test 4: Ten is greater than 5?");
console.log(ten > 5);
console.log("Test 5: 5 is smaller than 10");
console.log(five < 10);
console.log("Test 6: 10 is smaller than 5");
console.log(ten < 5);
console.log("Test 7: 5 is equal to 10");
console.log(five == 10);
